from pydantic import BaseModel, Field
from typing import List, Optional, Dict
from datetime import datetime
import uuid
import hashlib

def generate_stable_id(text: str) -> str:
    """Generates a stable slug-like ID from a string."""
    return text.lower().replace(" ", "-").replace("/", "-")[:50]

class Document(BaseModel):
    """Immutable source material uploaded by the user."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    filename: str
    content: str
    pages: int = 0
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())



class ConceptOutline(BaseModel):
    title: str
    type: str = "general"
    confidence: float = 1.0
    covers: List[str] = []
    slides: Optional[List[int]] = None

class TopicOutline(BaseModel):
    """Structured outline generated by the Planning Pass."""
    topic: str
    exam_focus: str
    concepts: List[ConceptOutline]

class LearningObject(BaseModel):
    """The fundamental unit of knowledge in the Folio architecture."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    stable_id: str
    document_id: str
    topic_label: str
    version: int = 1
    content_hash: str
    
    # LLM Generated Fields (The actual knowledge)
    title: str

    # Required sections
    definition: str
    explanation: str

    # Optional sections based on CapabilityProfile
    algorithm_steps: Optional[List[str]] = None
    formula: Optional[str] = None
    code_example: Optional[str] = None
    comparison_table: Optional[List[dict]] = None
    diagram_description: Optional[str] = None
    example: Optional[str] = None
    memory_trick: Optional[str] = None
    common_mistakes: Optional[str] = None
    prerequisites: Optional[List[str]] = None
    exam_tip: Optional[str] = None
    key_takeaways: Optional[List[str]] = None
    
    # Code Generated Fields
    keywords: List[str] = Field(default_factory=list)
    source_slides: List[int] = Field(default_factory=list)
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    
    # Deferred fields for Future Slices
    concept_id: Optional[str] = None
    related_ids: List[str] = Field(default_factory=list)
    embedding: Optional[str] = None
    study_priority: Optional[float] = None
    mastery_score: Optional[float] = None

    @classmethod
    def compute_hash(cls, text: str) -> str:
        """Computes a stable hash for checking if source content changed."""
        return hashlib.sha256(text.encode('utf-8')).hexdigest()

# Semantic alias for architectural clarity (Slice 10.6)
StudyTopic = LearningObject
