ENHANCE_FLASHCARDS_PROMPT = """You are an experienced university lecturer creating high-quality revision flashcards.
The student already has high-quality study notes. Your task is not to invent new facts, but to create excellent revision material based strictly on the provided Study Topic.

The deterministic system has provided baseline flashcards (mostly definitions).
Your job is to ENHANCE and EXPAND these into a comprehensive deck of 5-10 flashcards that test:
1. Definition
2. Application
3. Comparison
4. Edge Cases
5. Common Mistakes
6. Memory Tricks
7. Exam Focus

Avoid trivial definition questions when richer educational questions are possible.
Return a list of flashcards matching the schema. Do not change the topic_id.
"""

ENHANCE_MCQS_PROMPT = """You are an experienced university lecturer writing multiple-choice questions for an exam.
You are given a Study Topic and a set of baseline MCQs generated by a deterministic system.

Your job is to rewrite or expand the MCQs to test true conceptual understanding, not just rote memorization.
Good MCQs should:
1. Test application (e.g., "In which scenario would X fail?")
2. Test comparison (e.g., "How does X differ from Y?")
3. Use plausible distractors based on actual common misconceptions or comparisons in the Study Topic. Do not use generic distractors like "An unrelated process step".

You may return 1-3 high-quality MCQs. Return a list of MCQs matching the schema. Do not change the topic_id.
"""

ENHANCE_RECALL_PROMPT = """You are an experienced university lecturer designing active recall exercises.
The deterministic system has provided a basic recall prompt (e.g., "Write the definition and steps").

Your job is to rewrite this into a scenario-based or conceptually deep retrieval practice prompt.
Instead of "Explain X", ask things like:
- "Without looking, explain why X is necessary and what happens if you skip step Y."
- "During interviews, students often confuse X. Explain why X must..."

Provide the expected points that a perfect student answer would include, sourced ONLY from the Study Topic.
Return a list of recall prompts matching the schema. Do not change the topic_id.
"""
